### ISSUE TITLE
Windows 7 IE 11 performance issue

### ISSUE THREAD

**Issue by espensgr** [janl/mustache.js#501] opened 2015-10-13 09:14 UTC
hey.
I`m having some huge performance issues in windows 7 IE 11 on the feeds on this page: https://hem.no/kjope-bolig but also other feeds on the site.
It works in all other browsers i have tested, so it seems to be this browser in specific.
Anyone else seen performance issues on this browser or other IE browsers?
It doesn't seem too make a difference if the template is one field, the performance is the same.

**Comment by deadsource** [comment] 2015-10-13 11:48
Actually entering your website and scrolling a bit on it made my CPU fans work harder (Win7, Chrome). It might be an issue not related to mustache.js. I had the same experience when working on my personal blog whereas the cause for lag was the fact that all of my images were being re-sized on the web browser. I'm not saying the issue is the same as mine was. But as much as I've used mustache.js, I haven't had much CPU time dedicated to it, especially after the template was rendered.

**Comment by phillipj** [comment] 2015-10-13 12:28
@espensgr you'll have to elaborate what you mean by performance issues. What are you doing when these issues occur? E.g. while waiting for the estates to appear or when scrolling?

**Comment by espensgr** [comment] 2015-10-15 13:30
@deadsource that is a good point with the picture painting. They are ajax loading, but it may be that they are all loading at the same time. Will have a look at that, thanks!

@phillipj performance issues may not be the right word. The browser stops and are waiting for response.
It`s just on load, it just stop.

**Comment by phillipj** [comment] 2015-10-15 13:43
Have you tried measuring what's taking time? E.g. wrapping some timing functions around your code in three different stages; (1) AJAX request / response handlers, (2) where `mustache.render()` is called and (3) at the end where you are altering the DOM.

**Comment by phillipj** [comment] 2016-02-29 20:38
Closing this for now. Don't hesitate to re-open if you find the time to investigate this further.

**Closed by phillipj** 2016-02-29 20:38 UTC

**Comment by espensgr** [comment] 2016-03-03 10:43
I found the issue by the way. It was SVG painting that hogged the system. Polyfill for SVG fixed the issue.

**Comment by phillipj** [comment] 2016-03-03 10:58
Nice, thanks for replying 👌
