### ISSUE TITLE
How can a function could be called from json in mustache CLI?

### ISSUE THREAD

**Issue by ph1-xyz** [janl/mustache.js#747] opened 2020-03-18 19:38 UTC
Hi!
I'm trying to execute from mustacheCLI a function residing in the dataView.json. This brings me an error, saying that JSON cannot contain functions...

How can one use mustache's functionality to execute functions from CLI?

Thanks

**Comment by phillipj** [comment] 2020-03-18 20:41
Hi there!

The error you're describing is a JSON limitation; functions cannot be serialised into JSON.

So in #717 we allowed our CLI to be given a .js file as the view, instead of a .json file. If we use the test files ([`./test/_files/cli_js_view_with_function.js`](https://github.com/janl/mustache.js/blob/master/test/_files/cli_js_view_with_function.js) & [`./test/_files/cli_js_view_with_function.mustache`](https://github.com/janl/mustache.js/blob/master/test/_files/cli_js_view_with_function.mustache)) we got in this repo as an example, you could use the CLI to render the output:

```
$ mustache cli_js_view_with_function.js cli_js_view_with_function.mustache
```

Does that make sense?

**Comment by ph1-xyz** [comment] 2020-03-18 21:49
Thank you very much, I'm going to try immediately.

I also commented [here](https://github.com/janl/mustache.js/pull/717#issuecomment-600832440) explaining a bit what I was trying to do, hope what you just pointed out solves it!

**Comment by phillipj** [comment] 2020-03-28 23:28
Thanks for confirming it works as intended!

Good suggestion mentioning the fact that .js could also be used in addition to .json, feel free to open a PR with an improvement 😄 

Closing this for now as your question has been answered.

**Closed by phillipj** 2020-03-28 23:28 UTC
